name: Test Devcontainer Feature

on:
  push:
    branches: [0.0.1b/releaser-infra@tailnet-init]
  pull_request:
    branches: [0.0.1b/releaser-infra@tailnet-init]
  workflow_dispatch:

jobs:
  test-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Dev Container CLI
        run: |
          npm install -g @devcontainers/cli

      - name: Run tests
        run: |
          npx @devcontainers/cli features test
